controller_list:
  - name: ''
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

  - name: gripper_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: 
      - left_finger_1_joint
      - left_finger_2_joint
      - right_finger_1_joint
      - right_finger_2_joint

